### ISSUE TITLE
turtles/minute?

### ISSUE THREAD

**Issue by remi-daigle** [rystanley/TurtleSimulations#2]
should we also plot the first figure as turtles/minute so that efficiency can be optimized?

**Comment by rystanley** [comment]
Not sure I know exactly what you are referring to. I think that the observational hours is the easiest to interpret. The updated analysis code should reflect this.

**Comment by remi-daigle** [comment]
Sorry, wrote this a little too fast, I was thinking of this figure. I think it might be useful for the y-axis to be # turtle/min instead of just the #
![numberturtles samplingeffort](https://cloud.githubusercontent.com/assets/6750300/11707082/b7bca616-9ed5-11e5-8e85-31b7c344c79b.png)
That way you could see that the short events are awful in terms of CPUE (or at least turtles/min). The way it's plotted now, you would expect a more or less linear increase in the number of turtles found with increases in sampling event length. 

If I was trying to optimize my sampling design, I would want to see that the short sampling events are not worth the effort due to the low CPUE. The way the figure reads now, we see a peak in numbers, but is that due to a increase in effort (e.g. 60 min sampling is less effort that 140 mins).
